### ISSUE TITLE
User Accesses Account

### ISSUE THREAD

**Issue by kieranmiguel** [jleeboyd/family-bank-app#1]
### User Story
As a User, I want to access account details.

### Context / Additional Information
Given the user is on the dashboard of the app, and an account exists
### Acceptance Criteria
- [x] - Clicking the Account name, the user will be directed to the account details screen
- [x] - Details screen contains name, balance, transactional information
- [x] - Deposit/withdrawal options present
- [x] - Detailed history option present

-------------------

Given the user is on the dashboard of the app
When the user clicks on an account (if a account exists)
Then the user will be directed to the account details, including name, balance, transcripts for transactions, and deposit/withdraw buttons

**Comment by RealDogDad** [comment]
### User Story
As a User, I want to access account details.

### Context / Additional Information
Given the user is on the dashboard of the app, and an account exists
### Acceptance Criteria
- [ ] - Clicking the Account name, the user will be directed to the account details screen
- [ ] - Details screen contains name, balance, transactional information
- [ ] - Deposit/withdrawal options present

**Comment by Dylan-Riley** [comment]
@StopMakingUsernamesUnique Like, here is probably the issue you're working on to view account details, I've assigned you

**Comment by Dylan-Riley** [comment]
Don't have a handy link to the exact PR but this is functionality in the app
