### ISSUE TITLE
User opens add account dialog

### ISSUE THREAD

**Issue by kieranmiguel** [jleeboyd/family-bank-app#2]
### User Story
As a User, I want to add accounts.

### Context / Additional Information
Given the user is on the dashboard of the app
### Acceptance Criteria
- [x] - Clicking the add account button, the user is directed to the new account dialog
- [x] - New account dialog contains fields for account name and initial balance
- [x] - New account dialog contains save and cancel functions

---------

Given: The user is on the dashboard of the app
When: The user clicks on the add account button
Then: The new account dialog will appear, including an option for name and starting balance, as well as a save or cancel option.

**Comment by RealDogDad** [comment]
### User Story
As a User, I want to add accounts.

### Context / Additional Information
Given the user is on the dashboard of the app
### Acceptance Criteria
- [ ] - Clicking the add account button, the user is directed to the new account dialog
- [ ] - New account dialog contains fields for account name and initial balance
- [ ] - New account dialog contains save and cancel functions
