### ISSUE TITLE
User Makes new account

### ISSUE THREAD

**Issue by kieranmiguel** [jleeboyd/family-bank-app#3]
### User Story
As a User, I want to add accounts

### Context / Additional Information
Given the user is at the add account dialog, the required information is entered and, the initial balance is greater than 0
### Acceptance Criteria
- [x] - Clicking the save button, the new account is initialized
- [x] - The new account dialog closes
- [x] - The newly created account is visible from the dashboard

---------

Given: The user is on the add account dialog, and, the two text entry boxes for the name and starting balance are filled.
When: the user presses the save button
Then: A new account will be made, and the new account dialog will close.

**Comment by RealDogDad** [comment]
### User Story
As a User, I want to add accounts

### Context / Additional Information
Given the user is at the add account dialog, the required information is entered and, the initial balance is greater than 0
### Acceptance Criteria
- [ ] - Clicking the save button, the new account is initialized
- [ ] - The new account dialog closes
- [ ] - The newly created account is visible from the dashboard

**Comment by Dylan-Riley** [comment]
Can't say exactly which PR this was considered complete in, but functionality is in app
