### ISSUE TITLE
User cancels creating new account

### ISSUE THREAD

**Issue by kieranmiguel** [jleeboyd/family-bank-app#4]
### User Story
As a User, I want to add accounts

### Context / Additional Information
Given an open 'new account' dialog
### Acceptance Criteria
- [x] - Clicking cancel, the information fields are cleared and the new account dialog closes

-------------

Given: the user has opened the new account dialog
When: the user presses the cancel button
Then: the dialog will close, and any data in the text entry boxes will clear.

**Comment by RealDogDad** [comment]
### User Story
As a User, I want to add accounts

### Context / Additional Information
Given an open 'new account' dialog
### Acceptance Criteria
- [x] - Clicking cancel, the information fields are cleared and the new account dialog closes

**Comment by Dylan-Riley** [comment]
Pretty much baked into the built-in dialog functions. See PR 17
