### ISSUE TITLE
User opens deposits / withdrawals dialog

### ISSUE THREAD

**Issue by kieranmiguel** [jleeboyd/family-bank-app#5]
### User Story
As a Banker, I want to deposit and withdraw money from the account

### Context / Additional Information
Given the user has selected a valid account
### Acceptance Criteria
- [x] - Clicking the deposit/withdraw button, the deposit/withdrawal dialogue pops up
- [x] - The deposit/withdrawal dialog includes options for amount and memorandum (memo)
- [x] - The deposit/withdrawal dialog includes options for save and cancel

------------

Given: the user has selected an account and is on the account screen
When: the user selects the deposit / withdraw button
Then: the deposit /withdraw dialog will pop up, including options for amount and an added note. The save and cancel function are also available here.

**Comment by RealDogDad** [comment]
### User Story
As a Banker, I want to deposit and withdraw money from the account

### Context / Additional Information
Given the user has selected a valid account
### Acceptance Criteria
- [ ] - Clicking the deposit/withdraw button, the deposit/withdrawal dialogue pops up
- [ ] - The deposit/withdrawal dialog includes options for amount and memorandum (memo)
- [ ] - The deposit/withdrawal dialog includes options for save and cancel

**Comment by Dylan-Riley** [comment]
This should be two separate buttons "deposit" and "withdraw" but will be nearly the same function, just one negative.
