### ISSUE TITLE
Account Activity transactions arent showing current balance. 

### ISSUE THREAD

**Issue by kieranmiguel** [jleeboyd/family-bank-app#52]
### Context / Additional Information
Account activity should show date, amount, note, current balance. Currently do not show current balance, only shows amount twice. 
### Acceptance Criteria
- [ ] - Account Transactions show current balance
- [ ]
- [ ]

**Comment by Dylan-Riley** [comment]
Resolved by https://github.com/jleeboyd/family-bank-app/pull/78
