### ISSUE TITLE
User deposits / Withdraws

### ISSUE THREAD

**Issue by kieranmiguel** [jleeboyd/family-bank-app#6]
### User Story
As a Banker I want to deposit and withdraw money from the account

### Context / Additional Information
Given the deposits/withdrawals dialog is open and required information is valid
### Acceptance Criteria
- [x] - Clicking the Save button, the amount declared is added/deducted from the account declared
- [x] - Transaction information is added to account tracker
- [x] - Deposit/withdrawal dialog closes

----------

Given: deposits / withdrawals dialog is open, and note/amount boxes have data
When: user presses save button
Then: amount is added /subtracted to account grand total, new transaction transcript is added to account tracker including datetime, amount, current account balance, and note. Deposits dialog closes.

**Comment by RealDogDad** [comment]
### User Story
As a Banker I want to deposit and withdraw money from the account

### Context / Additional Information
Given the deposits/withdrawals dialog is open and required information is valid
### Acceptance Criteria
- [ ] - Clicking the Save button, the amount declared is added/deducted from the account declared
- [ ] - Transaction information is added to account tracker
- [ ] - Deposit/withdrawal dialog closes

**Comment by Dylan-Riley** [comment]
Don't have a link to the exact PR, but deposit and withdraw are working functions in the app
