### ISSUE TITLE
User cancels making withdrawal / deposit

### ISSUE THREAD

**Issue by kieranmiguel** [jleeboyd/family-bank-app#7]
### User Story
As a Banker I want to deposit and withdraw money from the account

### Context / Additional Information
Given the user is at the deposit/withdrawal dialog
### Acceptance Criteria
- [x] - Clicking the cancel button, information fields are cleared and dialog closes

------------

Given: User is on withdrawal / deposits dialog 
When: User presses cancel button
Then: Text entry boxes are cleared, dialog closes.

**Comment by RealDogDad** [comment]
### User Story
As a Banker I want to deposit and withdraw money from the account

### Context / Additional Information
Given the user is at the deposit/withdrawal dialog
### Acceptance Criteria
- [ ] - Clicking the cancel button, information fields are cleared and dialog closes

**Comment by Dylan-Riley** [comment]
Closed because this ends up being default behavior of the dialog
